kind: ConfigMap
apiVersion: v1
metadata:
  name: workbench-{{ WORKBENCH_NAME }}-default
  namespace: {{ WORKBENCH_NAMESPACE }}
data:
  USING_OPENSHIFT_AI: 'true'
  OPENSHIFT_APPS_DOMAIN: '{{ OPENSHIFT_APPS_DOMAIN }}'
  OPENSHIFT_AI_WORKBENCH: {{ WORKBENCH_NAME }}
  WORKBENCH_ADMIN: '{{ WORKBENCH_ADMIN | string | lower }}'
  SITE_NAMESPACE: {{ WORKBENCH_NAMESPACE }}
  SITE_HOST_NAME: '{{ SITE_SHORT_NAME }}-{{ USER_NAME }}.{{ OPENSHIFT_APPS_DOMAIN }}'
  SITE_BASE_URL: 'https://{{ SITE_SHORT_NAME }}-{{ USER_NAME }}.{{ OPENSHIFT_APPS_DOMAIN }}'
  ZOOKEEPER_ROOT_PATH: '{{ SITE_SHORT_NAME }}-{{ USER_NAME }}'
  SSL_VERIFY: 'true'
  ZOOKEEPER_NAMESPACE: zookeeper
  ZOOKEEPER_HOST_NAME: zookeeper.zookeeper.svc
  ZOOKEEPER_PORT: '2181'
  SOLR_NAMESPACE: solr
  SOLR_HOST_NAME: solr.solr.svc
  SOLR_PORT: '8983'
  SOLR_SSL: 'false'
  SOLR_COLLECTION_COMPUTATE: 'computate-{{ USER_NAME }}'
  SOLR_COLLECTION_FIWARE: 'fiware'
  COMPUTATE_SEARCH_SRC: '/opt/app-root/src/computate-search'
  COMPUTATE_VERTX_SRC: '/opt/app-root/src/computate-vertx'
  COMPUTATE_SRC: '/opt/app-root/src/computate'
  CONTEXT_BROKER_NAMESPACE: "scorpiobroker"
  CONTEXT_BROKER_SSL: "false"
  CONTEXT_BROKER_HOST_NAME: "scorpiobroker.scorpiobroker.svc"
  CONTEXT_BROKER_PORT: "9090"
  NGSILD_TENANT: "{{ SITE_SHORT_NAME }}-{{ USER_NAME }}"
  NGSILD_PATH: "/USA"
  NGSILD_TENANT_ENV: "NGSILD_TENANT"
  NGSILD_PATH_ENV: "NGSILD_PATH"
  ENABLE_FIWARE: "{{ ENABLE_FIWARE | string | lower }}"
  DATABASE_HOST_NAME: "postgres-primary.postgres.svc"
  DATABASE_PORT: "5432"
  SITE_POWERED_BY_NAME: "Red Hat Demo Platform"
  SITE_POWERED_BY_URL: "https://catalog.demo.redhat.com"
  ENABLE_MQTT: 'true'
  MQTT_NAMESPACE: amq-broker
  MQTT_PORT: '1883'
  MQTT_HOST_NAME: "import-broker-mqtt-0-svc.amq-broker.svc"
  MQTT_USER: "user"
  MQTT_PASSWORD: "password"
