apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-admin-{{ SITE_NAME }}
  namespace: {{ WORKBENCH_NAMESPACE }}
type: Opaque
stringData:
  password: "{{ lookup('env', 'AUTH_ADMIN_PASSWORD') }}"
  username: "{{ lookup('env', 'AUTH_ADMIN_USERNAME') }}"
