apiVersion: v1
kind: ConfigMap
data:
  main.yaml: |
    - name: "Clone {{ SITE_NAME }} project"
      tags:
        - clone-repos
        - skip-clone-repos
      kubernetes.core.k8s_exec:
        namespace: "{{ WORKBENCH_NAMESPACE }}"
        pod: "{{ WORKBENCH_NAME }}-0"
        command: >-
          bash -c '
          rm -rf {{ SITE_SRC }};
          git clone https://github.com/{{ GITHUB_ORG }}/{{ SITE_NAME }}.git {{ SITE_SRC }};
          (cd {{ SITE_SRC }} && mvn clean install)
          '
    - name: "Clone {{ SITE_NAME }}-static project"
      tags:
        - clone-repos
        - skip-clone-repos
      kubernetes.core.k8s_exec:
        namespace: "{{ WORKBENCH_NAMESPACE }}"
        pod: "{{ WORKBENCH_NAME }}-0"
        command: >-
          bash -c '
          rm -rf {{ SITE_SRC }}-static;
          git clone https://github.com/{{ GITHUB_ORG }}/{{ SITE_NAME }}-static.git {{ SITE_SRC }}-static;
          '
    - name: "Index the {{ SITE_NAME }} classes"
      tags:
        - index-classes
        - skip-index-classes
      kubernetes.core.k8s_exec:
        namespace: "{{ WORKBENCH_NAMESPACE }}"
        pod: "{{ WORKBENCH_NAME }}-0"
        command: >-
          bash -i -c '
            cd /opt/app-root/src;
            eval $(./vars.py);
            env VARS_PATH=$SITE_SRC/vars.yaml \
              SITE_PATH=$SITE_SRC \
              COMPUTATE_SRC=$COMPUTATE_SRC \
              COMPUTATE_VERTX_SRC=$COMPUTATE_VERTX_SRC \
              SITE_LANG=enUS \
              $COMPUTATE_SRC/bin/enUS/index.sh
            '
