apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-certificate
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
  secretName: keycloak-certificate
  duration: 2160h
  isCA: false
  renewBefore: 360h
  commonName: "{{ AUTH_HOST_NAME }}"
  dnsNames:
    - "{{ AUTH_HOST_NAME }}"
