apiVersion: v1
kind: Secret
metadata:
  name: postgres-pguser-keycloak
  namespace: keycloak
type: Opaque
stringData:
  user: keycloak
  password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='postgres-pguser-keycloak', namespace='postgres')[0].data['password'] | b64decode }}"
