apiVersion: v1
kind: ConfigMap
metadata:
  name: deploy-workbench-playbook
  namespace: {{ WORKBENCH_NAMESPACE }}
data:
  deploy-workbench.yaml: |
    ---
    - name: Deploy workbench
      hosts: localhost
      connection: local
      gather_facts: false
      roles:
        - deploy-workbench
