apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-{{ SITE_SHORT_NAME }}
  namespace: {{ WORKBENCH_NAMESPACE }}
type: Opaque
stringData:
  clientId: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-client-' + SITE_NAME), namespace=AUTH_NAMESPACE)[0].data['client'] | b64decode }}"
  clientSecret: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-client-' + SITE_NAME), namespace=AUTH_NAMESPACE)[0].data['secret'] | b64decode }}"
