apiVersion: v1
kind: Secret
metadata:
  name: postgres-pguser-{{ DATABASE_USERNAME }}
  namespace: {{ WORKBENCH_NAMESPACE }}
type: Opaque
stringData:
  password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('postgres-pguser-' + DATABASE_USERNAME), namespace='postgres')[0].data['password'] | b64decode }}"
