apiVersion: v1
kind: Secret
metadata:
  name: font-awesome
  namespace: {{ SITE_NAMESPACE }}
type: Opaque
stringData:
  WEB_COMPONENTS_PREFIX: "{{ lookup('env', 'WEB_COMPONENTS_PREFIX') | default('sl-', true) }}"
  WEB_COMPONENTS_SECRET: "{{ lookup('env', 'WEB_COMPONENTS_SECRET') | default('font-awesome', true) }}"
  WEB_COMPONENTS_CSS: "{{ lookup('env', 'WEB_COMPONENTS_CSS') | default('<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.20.0/cdn/themes/light.css" />', true) }}"
  WEB_COMPONENTS_JS: "{{ lookup('env', 'WEB_COMPONENTS_JS') | default('<script type="module" src="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.20.0/cdn/shoelace-autoloader.js"></script>', true) }}"
  FONTAWESOME_KIT: "{{ lookup('env', 'FONTAWESOME_KIT') | default('', true) }}"
  FONTAWESOME_STYLE: "{{ lookup('env', 'FONTAWESOME_STYLE') | default('fa-duotone fa-regular ', true) }}"
  SITE_THEME: "{{ lookup('env', 'SITE_THEME') | default('dark', true) }}"
