---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ WORKBENCH_NAMESPACE }}-keycloak-secrets
  namespace: "{{ AUTH_NAMESPACE }}"
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ WORKBENCH_NAMESPACE }}-keycloak-secrets
  namespace: "{{ AUTH_NAMESPACE }}"
subjects:
  - kind: ServiceAccount
    name: {{ WORKBENCH_NAME }}
    namespace: {{ WORKBENCH_NAMESPACE }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ WORKBENCH_NAMESPACE }}-keycloak-secrets