---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ WORKBENCH_NAMESPACE }}-keycloak-secrets
  namespace: "{{ AUTH_NAMESPACE }}"
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ WORKBENCH_NAMESPACE }}-keycloak-secrets
  namespace: "{{ AUTH_NAMESPACE }}"
subjects:
  - kind: ServiceAccount
    name: {{ WORKBENCH_NAME }}
    namespace: {{ WORKBENCH_NAMESPACE }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ WORKBENCH_NAMESPACE }}-keycloak-secrets
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: solr-exec-user
  namespace: solr
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ WORKBENCH_NAMESPACE }}-exec
  namespace: solr
subjects:
  - kind: ServiceAccount
    name: deploy-workbench
    namespace: {{ WORKBENCH_NAMESPACE }}
  - kind: ServiceAccount
    name: {{ WORKBENCH_NAME }}
    namespace: {{ WORKBENCH_NAMESPACE }}
  - kind: User
    name: {{ USER_NAME }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: solr-exec-user