---

- name: "Install cluster-admin ClusterRoleBinding for group {{ CLUSTER_ADMIN_GROUP }} on OpenShift"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'cluster-admin-group-role-binding.yaml') }}"
    validate_certs: false

- name: Configure keycloak realm
  community.general.keycloak_realm:
    validate_certs: false
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ AUTH_URL }}"
    auth_realm: master
    auth_username: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['username'] | b64decode }}"
    auth_password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['password'] | b64decode }}"
    state: present
    id: "{{ AUTH_REALM }}"
    realm: "{{ AUTH_REALM }}"
    enabled: true
    displayName: "{{ AUTH_REALM }}"
    registrationAllowed: false
    resetPasswordAllowed: true
    editUsernameAllowed: false
    rememberMe: true
    verifyEmail: false
    loginWithEmailAllowed: false

- name: "Configure keycloak client scope openid"
  community.general.keycloak_clientscope:
    validate_certs: false
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ AUTH_URL }}"
    auth_realm: master
    auth_username: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['username'] | b64decode }}"
    auth_password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['password'] | b64decode }}"
    state: present
    id: "{{ AUTH_REALM }}-openid"
    realm: "{{ AUTH_REALM }}"
    name: "openid"
    description: A client scope for the openid client
    protocol: openid-connect
    attributes:
      include.in.token.scope: 'true'
    protocolMappers:
      - config:
          access.token.claim: 'true'
          introspection.token.claim: 'true'
        id: "{{ AUTH_REALM }}-openid-sub"
        name: "sub"
        protocol: openid-connect
        protocolMapper: oidc-sub-mapper

- name: "Configure keycloak client scope {{ AUTH_CLIENT }}"
  community.general.keycloak_clientscope:
    validate_certs: false
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ AUTH_URL }}"
    auth_realm: master
    auth_username: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['username'] | b64decode }}"
    auth_password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['password'] | b64decode }}"
    state: present
    id: "{{ AUTH_REALM }}-{{ AUTH_CLIENT }}"
    realm: "{{ AUTH_REALM }}"
    name: "{{ AUTH_CLIENT }}"
    description: A client scope for the {{ AUTH_CLIENT }} client
    protocol: openid-connect
    attributes:
      include.in.token.scope: 'true'
    protocolMappers:
      - config:
          access.token.claim: 'true'
          id.token.claim: 'false'
          included.client.audience: '{{ AUTH_CLIENT }}'
        id: "{{ AUTH_REALM }}-{{ AUTH_CLIENT }}"
        name: "{{ AUTH_CLIENT }}"
        protocol: openid-connect
        protocolMapper: oidc-audience-mapper

- name: "Disable RSA-OAEP key component from {{ AUTH_REALM }}"
  community.general.keycloak_component:
    validate_certs: false
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ AUTH_URL }}"
    auth_realm: master
    auth_username: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['username'] | b64decode }}"
    auth_password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['password'] | b64decode }}"
    state: absent
    name: rsa-enc-generated
    parent_id: "{{ AUTH_REALM }}"
    provider_id: rsa-enc-generated
    provider_type: org.keycloak.keys.KeyProvider

- name: "Configure OpenShift client {{ AUTH_CLIENT }}"
  community.general.keycloak_client:
    state: present
    validate_certs: false
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ AUTH_URL }}"
    auth_realm: master
    auth_username: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['username'] | b64decode }}"
    auth_password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['password'] | b64decode }}"
    realm: "{{ AUTH_REALM }}"
    id: "{{ AUTH_CLIENT }}"
    name: "{{ AUTH_CLIENT }}"
    clientId: "{{ AUTH_CLIENT }}"
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    authorizationServicesEnabled: true
    frontchannelLogout: true
    publicClient: false
    protocol: openid-connect
    redirectUris: "{{ lookup('template', 'keycloak-redirect-uris.yaml') | from_yaml }}"
    defaultClientScopes:
      - openid
      - profile
      - "{{ AUTH_CLIENT }}"
    authorizationSettings:
      decisionStrategy: AFFIRMATIVE
#
#- name: "Install keycloak-identity-provider secret on OpenShift"
#  kubernetes.core.k8s:
#    state: present
#    definition: "{{ lookup('template', 'keycloak-identity-provider-secret.yaml') }}"
#    validate_certs: false
#  when: (query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-identity-provider'), namespace='keycloak')[0].data['GITHUB_AUTH_SECRET'] | default('')) == ''
#
#- name: Configure Keycloak GitHub identity provider
#  community.general.keycloak_identity_provider:
#    state: present
#    validate_certs: false
#    auth_client_id: admin-cli
#    auth_keycloak_url: "{{ AUTH_URL }}"
#    auth_realm: master
#    auth_username: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['username'] | b64decode }}"
#    auth_password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['password'] | b64decode }}"
#    enabled: true
#    realm: "{{ AUTH_REALM }}"
#    providerId: openshiftv4
#    alias: openshift
#    displayName: OpenShift
#    trustEmail: true
#    storeToken: false
#    addReadTokenRoleOnCreate: false
#    authenticateByDefault: false
#    linkOnly: false
#    config:
#      syncMode: "LEGACY"
#      clientId: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-identity-provider'), namespace='keycloak')[0].data['GITHUB_AUTH_CLIENT'] | b64decode }}"
#      clientSecret: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-identity-provider'), namespace='keycloak')[0].data['GITHUB_AUTH_SECRET'] | b64decode }}"
#
#- name: "Install group-sync-operator bundle on OpenShift"
#  kubernetes.core.k8s:
#    state: present
#    definition: "{{ lookup('kubernetes.core.kustomize', dir='kustomize/cluster-scope/bundles/group-sync-operator/') }}"
#    validate_certs: false
#- name: "Install github-group-sync secret on OpenShift"
#  kubernetes.core.k8s:
#    state: present
#    definition: "{{ lookup('template', 'github-group-sync-secret.yaml') }}"
#    validate_certs: false
#  when: (query('kubernetes.core.k8s', kind='Secret', resource_name=('github-group-sync'), namespace='group-sync-operator')[0].data['privateKey'] | default('')) == ''
#- name: "Install groupsync on OpenShift"
#  kubernetes.core.k8s:
#    state: present
#    definition: "{{ lookup('template', 'groupsync.yaml') }}"
#    validate_certs: false
#
#- name: "Install OAuth with GITHUB_OPENSHIFT_CLIENT on OpenShift"
#  kubernetes.core.k8s:
#    state: present
#    definition: "{{ lookup('template', 'oauth.yaml') }}"
#    validate_certs: false
