---
- name: "Deploy keycloak cluster-scope bundle on OpenShift"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='bundles/keycloak/') }}"
- name: Wait for keycloak operator Ready condition
  kubernetes.core.k8s_info:
    namespace: keycloak
    kind: Pod
    label_selectors:
      - name=rhbk-operator
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: 'True'
- name: "Install database secret on OpenShift"
  register: r_k8s_secret
  kubernetes.core.k8:
    state: present
    definition: "{{ lookup('template', 'postgres-pguser-keycloak-secret.yaml') }}"
  until: r_k8s_secret is success
  retries: 20
  delay: 30
- name: "Deploy keycloak certificate on OpenShift"
  register: r_k8s_cert
  kubernetes.core.k8s:
    state: present
    namespace: keycloak
    definition: "{{ lookup('template', 'certificate.yaml') }}"
  until: r_k8s_cert is success
  retries: 20
  delay: 30
- name: "Deploy keycloak on OpenShift"
  kubernetes.core.k8s:
    state: present
    namespace: keycloak
    definition: "{{ lookup('template', 'keycloak.yaml') }}"
  retries: 20
  delay: 30
- name: Wait for keycloak Ready condition
  kubernetes.core.k8s_info:
    namespace: keycloak
    kind: Pod
    label_selectors:
      - app=keycloak
      - apps.kubernetes.io/pod-index=0
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: 'True'
