apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: import-broker
  namespace: amq-broker
spec:
  acceptors:
    - name: mqtt
      protocols: mqtt
      port: 1883
    - name: amqp
      protocols: amqp
      port: 5672
  console:
    expose: true
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 2
    resources:
      limits:
        cpu: '1'
        memory: '4Gi'
      requests:
        cpu: '1'
        memory: '1Gi'
