apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      bundle: amq-broker
    includeSelectors: true
resources:
  - ../../base/core/namespaces/amq-broker
  - ../../base/operators.coreos.com/subscriptions/amq-broker-rhel8
