---

- name: Get a new Keycloak client secret, passing client_id instead of id
  community.general.keycloak_clientsecret_info:
    validate_certs: false
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ AUTH_URL }}"
    auth_realm: master
    auth_username: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace=AUTH_NAMESPACE)[0].data['username'] | b64decode }}"
    auth_password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace=AUTH_NAMESPACE)[0].data['password'] | b64decode }}"
    client_id: '{{ AUTH_CLIENT }}'
    realm: "{{ AUTH_REALM }}"
  register: AUTH_CLIENT_SECRET
- name: "Deploy workbenches"
  include_tasks: deploy-workbench.yaml
  loop: "{{ WORKBENCH_NAMES }}"
  vars:
    WORKBENCH_NAMESPACE: "workbench-{{ WORKBENCH_VARS.USER_NAME }}"
    WORKBENCH_NAME: "vscode"
    USER_NAME: "{{ WORKBENCH_VARS.USER_NAME }}"
    WORKBENCH_ADMIN: "{{ WORKBENCH_VARS.WORKBENCH_ADMIN is defined and WORKBENCH_VARS.WORKBENCH_ADMIN | bool }}"
    DATABASE_USERNAME: "{{ SITE_SHORT_NAME }}{{ WORKBENCH_VARS.USER_NAME | replace('-', '') | replace('_', '') }}"
    DATABASE_DATABASE: "{{ SITE_SHORT_NAME }}{{ WORKBENCH_VARS.USER_NAME | replace('-', '') | replace('_', '') }}"
    SOLR_COLLECTION: '{{ SITE_SHORT_NAME }}-{{ WORKBENCH_VARS.USER_NAME }}'
    SOLR_COLLECTION_COMPUTATE: 'computate-{{ WORKBENCH_VARS.USER_NAME }}'
  tags:
    - deploy-notebooks
    - deploy-rolebindings
    - deploy-configmaps
    - deploy-vars
    - create-database
  loop_control:
    loop_var: WORKBENCH_VARS
    index_var: WORKBENCH_INDEX
