---

- name: "Create a default font-awesome secret in namespace {{ SITE_NAMESPACE }}"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'shoelace-secret.yaml') }}"
    validate_certs: false
  ignore_errors: true
- name: Get a new Keycloak client secret, passing client_id instead of id
  community.general.keycloak_clientsecret_info:
    validate_certs: false
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ AUTH_URL }}"
    auth_realm: master
    auth_username: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace=AUTH_NAMESPACE)[0].data['username'] | b64decode }}"
    auth_password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace=AUTH_NAMESPACE)[0].data['password'] | b64decode }}"
    client_id: '{{ AUTH_CLIENT }}'
    realm: "{{ AUTH_REALM }}"
  register: AUTH_CLIENT_SECRET
- name: "Deploy workbenches"
  include_tasks: deploy-workbench.yaml
  vars:
    WORKBENCH_NAMESPACE: "workbench-{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    WORKBENCH_NAME: "vscode"
    USER_NAME: "{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    WORKBENCH_ADMIN: "{{ WORKBENCH_NUM == 0 }}"
    DATABASE_USERNAME: "{{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    DATABASE_DATABASE: "{{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    SOLR_COLLECTION: "{{ SITE_SHORT_NAME }}-{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    SOLR_COLLECTION_COMPUTATE: "computate-{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
  tags:
    - deploy-notebooks
    - deploy-rolebindings
    - deploy-configmaps
    - deploy-vars
    - create-database
  loop: "{{ range(0, (WORKBENCH_COUNT | int) + 1, 1) | list }}"
  loop_control:
    loop_var: WORKBENCH_NUM
    index_var: WORKBENCH_INDEX
