---
- name: "Deploy crunchy-postgres-operator cluster-scope bundle on OpenShift"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='bundles/crunchy-postgres-operator/') }}"
- name: "Deploy postgres cluster-scope bundle on OpenShift"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='bundles/postgres/') }}"
- name: Wait for crunchy-postgres-operator Ready condition
  kubernetes.core.k8s_info:
    namespace: openshift-operators
    kind: Pod
    label_selectors:
      - postgres-operator.crunchydata.com/control-plane=postgres-operator
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: 'True'
- name: "Deploy the PostgresCluster with user workbenches"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'postgrescluster.yaml') }}"
    validate_certs: false
- name: Wait for postgres Ready condition
  kubernetes.core.k8s_info:
    namespace: postgres
    kind: Pod
    label_selectors:
      - postgres-operator.crunchydata.com/role=master
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: 'True'
