---

- name: "Deploy workbenches"
  include_tasks: clone-github-repo.yaml
  vars:
    WORKBENCH_NAMESPACE: "workbench-{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    WORKBENCH_NAME: "vscode"
    USER_NAME: "{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    WORKBENCH_ADMIN: "{{ WORKBENCH_NUM == 0 }}"
    DATABASE_USERNAME: "{{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    DATABASE_DATABASE: "{{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    SOLR_COLLECTION: "{{ SITE_SHORT_NAME }}-{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
    SOLR_COLLECTION_COMPUTATE: "computate-{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
  loop: "{{ range(0, (WORKBENCH_COUNT | int) + 1, 1) | list }}"
  loop_control:
    loop_var: WORKBENCH_NUM
    index_var: WORKBENCH_INDEX
