apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: github
  namespace: group-sync-operator
spec:
  # synchronize every 4 hours
  schedule: "*/10 * * * *"
  providers:
    - name: keycloak
      keycloak:
        realm: {{ AUTH_REALM }}
        credentialsSecret:
          name: openshift-group-sync
          namespace: group-sync-operator
        url: {{ AUTH_URL }}
