apiVersion: v1
kind: Secret
metadata:
  namespace: group-sync-operator
  name: openshift-group-sync
type: Opaque
stringData:
  username: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['username'] | b64decode }}"
  password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=('keycloak-initial-admin'), namespace='keycloak')[0].data['password'] | b64decode }}"
