apiVersion: v1
kind: Service
metadata:
  name: scorpiobroker
  namespace: scorpiobroker
  labels:
    app.kubernetes.io/instance: scorpiobroker
    app.kubernetes.io/name: scorpiobroker
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/instance: scorpiobroker
    app.kubernetes.io/name: scorpiobroker
  type: ClusterIP
