apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: postgres
spec:
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-2
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      replicas: 1
      name: 'postgres'
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-15.1-3.3-0
  postgresVersion: 15
  openshift: true
  postGISVersion: 3.3.0
  users:
    - name: keycloak
      options: "SUPERUSER"
      databases:
        - keycloak
    - name: "smartaquaculture"
      options: "SUPERUSER"
      databases:
        - "smartaquaculture"
    - name: "scorpiobroker"
      options: "SUPERUSER CREATEDB"
      databases:
        - "scorpiobroker"
{% for WORKBENCH_NUM in range(0, (WORKBENCH_COUNT | int) + 1, 1) | list %}
    - name: "{{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
      options: "SUPERUSER"
      databases:
        - "{{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }}"
{% endfor %}
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "host keycloak keycloak all md5"
          - "local keycloak keycloak trust"
          - "host smartaquaculture smartaquaculture all md5"
          - "local smartaquaculture smartaquaculture trust"
          - "host all scorpiobroker all md5"
          - "local all scorpiobroker trust"
{% for WORKBENCH_NUM in range(0, (WORKBENCH_COUNT | int) + 1, 1) | list %}
          - "host {{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }} {{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }} all md5"
          - "local {{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }} {{ SITE_SHORT_NAME }}{{ 'computate' if WORKBENCH_NUM == 0 else 'user' + (WORKBENCH_NUM | string) }} trust"
{% endfor %}
