apiVersion: v1
kind: Secret
metadata:
  name: postgres-pguser-scorpiobroker
  namespace: scorpiobroker
type: Opaque
stringData:
  password: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='postgres-pguser-scorpiobroker', namespace='postgres')[0].data['password'] | b64decode }}"
