apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      bundle: rhods-operator
    includeSelectors: true
resources:
  - ../../base/core/namespaces/redhat-ods-operator
  - ../../base/operators.coreos.com/operatorgroups/redhat-ods-operator
  - ../../base/operators.coreos.com/subscriptions/redhat-ods-operator
