---
- name: "Deploy zookeeper cluster-scope bundle on OpenShift"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='bundles/zookeeper/') }}"
- name: "Deploy zookeeper on OpenShift"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('kubernetes.core.kustomize', dir='features/zookeeper/') }}"
- name: Wait for zookeeper Ready condition
  kubernetes.core.k8s_info:
    namespace: zookeeper
    kind: Pod
    label_selectors:
      - app.kubernetes.io/name=zookeeper
      - apps.kubernetes.io/pod-index=0
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: 'True'
